<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">execGroovyScript</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gSW5wdXQgWE1MIHN0cmluZwpTdHJpbmcgeG1sSW5wdXQgPSAiIiIKICAgICAgICA8Ym9va3M+
CiAgICAgICAgICAgIDxib29rIHRpdGxlPSIxOTg0IiBhdXRob3I9Ikdlb3JnZSBPcndlbGwiLz4K
ICAgICAgICAgICAgPGJvb2sgdGl0bGU9IkJyYXZlIE5ldyBXb3JsZCIgYXV0aG9yPSJBbGRvdXMg
SHV4bGV5Ii8+CiAgICAgICAgPC9ib29rcz4KICAgICAgICAiIiI7CgpQYXRoIGN1cnJlbnRSZWxh
dGl2ZVBhdGggPSBQYXRocy5nZXQoIiIpOwpTdHJpbmcgcyA9IGN1cnJlbnRSZWxhdGl2ZVBhdGgu
dG9BYnNvbHV0ZVBhdGgoKS50b1N0cmluZygpOwpTeXN0ZW0ub3V0LnByaW50bG4oIkN1cnJlbnQg
YWJzb2x1dGUgcGF0aCBpczogIiArIHMpOwogIAovLyBMb2FkIGV4dGVybmFsIHNjcmlwdAoKRmls
ZSBzY3JpcHRGaWxlID0gbmV3IEZpbGUocyArIi9wYWNrYWdlcy9Hcm9vdnlEZW1vL3NjcmlwdHMv
bW9kaWZ5WG1sLmdyb292eSIpOyAvLyBwYXRoIHRvIHlvdXIgc2NyaXB0ClN0cmluZyBzY3JpcHRD
b250ZW50ID0gbnVsbDsKdHJ5IHsKCXNjcmlwdENvbnRlbnQgPSBGaWxlcy5yZWFkU3RyaW5nKHNj
cmlwdEZpbGUudG9QYXRoKCkpOwp9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7CgkvLyBUT0RPIEF1
dG8tZ2VuZXJhdGVkIGNhdGNoIGJsb2NrCgllLnByaW50U3RhY2tUcmFjZSgpOwp9CgovLyBQcmVw
YXJlIHRoZSBiaW5kaW5nCkJpbmRpbmcgYmluZGluZyA9IG5ldyBCaW5kaW5nKCk7CmJpbmRpbmcu
c2V0VmFyaWFibGUoImlucHV0WG1sIiwgeG1sSW5wdXQpOwoKLy8gRXhlY3V0ZSB0aGUgR3Jvb3Z5
IHNjcmlwdApHcm9vdnlTaGVsbCBzaGVsbCA9IG5ldyBHcm9vdnlTaGVsbChiaW5kaW5nKTsKT2Jq
ZWN0IHJlc3VsdCA9IHNoZWxsLmV2YWx1YXRlKHNjcmlwdENvbnRlbnQpOwoKU3lzdGVtLm91dC5w
cmludGxuKCJNb2RpZmllZCBYTUw6XG4iICsgcmVzdWx0KTs=</value>
</Values>
